### ISSUE TITLE
Defining data source and mapping columns for a working yesoreyeram-infinity-datasource in a Scenes App

### ISSUE THREAD

**Issue by allomorphy** [grafana/scenes#1017]
Hi Scenes experts,

Thank you for Scenes, an amazing leap forward in Grafana.

We are not achieving a working  definition of the Infinity json datasource in a `queryRunner` despite trying various approaches.  We are using a provisioned version of  the fine yesoreyeram-infinity-datasource at https://github.com/grafana/grafana-infinity-datasource

We use as shown below under the following header and it works fine in the base GF instance in which the App itself is running. 
--------- standard dashboard working version --------------
A key to solving  this issue seems to be to transform the data by mapping columns. We are not sure how to implement this with the typescript in the Scenes definition.

We have the app-with-scenes example  from https://github.com/grafana/grafana-plugin-examples working as an App in in our existingWorld 
In the `helloWorldScene.tsx`, we try
`uid: 'DS_INFINITY' ` This is a template variable mapping that works in the standard dashboard in the same GF instance.

The attempt to use ${} instead of bare notation failed with "cannot find datasource".

Our attempt below under this header FAILS:
====== helloWorldScene.tsx  from https://github.com/grafana/grafana-plugin-examples ============

ERROR: Cannot read properties of undefined (reading 'method')

The snippets we have found below do not help us to achieve a working version or give enough understanding to adapt our existing code.

From https://github.com/grafana/scenes/blob/main/docusaurus/docs/advanced-data.tsx
...................................................................
```
export function getAdvancedDataScene() {
  const data = new SceneQueryRunner({
    datasource: {
      type: 'prometheus',
      uid: 'gdev-prometheus',
    },
    queries: [
      {
        refId: 'A',
        expr: 'rate(prometheus_http_requests_total{}[5m])',
      },
    ],
  });
```
...................................................................
We did not find enough in the this doc from the scenes repo either: 
docusaurus/docs/advanced-data.md

So far the debug logs are not giving me much insight either, so it feels a bit like working blind.

It would be great to receive some proposals to attempt and I will report back here and to the Infinity plugin community here:
https://github.com/grafana/grafana-infinity-datasource/discussions/1098 

Best wishes
E

--------- standard dashbord working version --------------
 ```
 "pluginVersion": "11.4.0",
  "targets": [
    {
      "columns": [
        {
          "selector": "sessionlabel",
          "text": "Session",
          "type": "string"
        },
        {
          "selector": "value",
          "text": "Result",
          "type": "number"
        },
        {
          "selector": "time",
          "text": "Time",
          "type": "timestamp_epoch"
        },
        {
          "selector": "analyte",
          "text": "Test",
          "type": "string"
        },
        {
          "selector": "measurementSeries",
          "text": "Session Date",
          "type": "string"
        }
      ],
      "datasource": {
        "type": "yesoreyeram-infinity-datasource",
        "uid": "${DS_INFINITY}"
      },
      "filters": [],
      "format": "timeseries",
      "global_query_id": "",
      "hide": false,
      "refId": "A",
      "root_selector": "",
      "source": "url",
      "type": "json",
      "url": "/v2/getkrafttimeshift/${__user.email}/${subject}/${lookupsetrecordskraftsingle}/${lookupsetrecordskraftsingle}/aintKetone",
      "url_options": {
        "data": "",
        "method": "GET"
      }
    }
```
----------------------

====== helloWorldScene.tsx  from https://github.com/grafana/grafana-plugin-examples ============
NOT WORKING 
FAILS WITH `Cannot read properties of undefined (reading 'method')`
```
 const datasource: DataSourceRef = {                                                                                                                                                         
    type: 'yesoreyeram-infinity-datasource',                                                                                                                                                  
    uid: 'DS_INFINITY'                                                                                                                                                                        
  }; 
  
  queryRunner3 = new SceneQueryRunner({                                                                                                                                                 
    datasource,                                                                                                                                                                               
    queries: [                                                                                                                                                                                
      {                                                                                                                                                                                       
        refId: 'C',                                                                                                                                                                           
        url: 'https://api.foobar.org/etcetcetc',                                                                                          
        method: 'GET',                                                                                                                                                                        
        source: 'url',                                                                                                                                                                        
        type: 'json',                                                                                                                                                                         
        root_selector: '$',                                                                                                                                                                   
        columns: [                                                                                                                                                                            
          {                                                                                                                                                                                   
            selector: "analyte",                                                                                                                                                              
            text: "analyte",                                                                                                                                                                  
            type: "string"                                                                                                                                                                    
          },                                                                                                                                                                                  
          {                                                                                                                                                                                   
            selector: "value",                                                                                                                                                                
            text: "value",                                                                                                                                                                    
            type: "number"                                                                                                                                                                    
          },                                                                                                                                                                                  
          {                                                                                                                                                                                   
            selector: "time",                                                                                                                                                                 
            text: "time",                                                                                                                                                                     
            timestampFormat: "2006-01-02T15:04:05Z07:00",                                                                                                                                     
            type: "timestamp_epoch"                                                                                                                                                           
          }                                                                                                                                                                                   
        ],                                                                                                                                                                                    
      },                                                                                                                                                                                      
    ],                                                                                                                                                                                        
  });   
```

**Comment by allomorphy** [comment]
[SOLVED]
We now have a working solution for timeseries as shown below 
If it is interesting to others to save the time to get fast to this solution, then happy to contribute a howto in this scenes or infinity projects 🤗 

The other graph types or members of PanelBuilders work too.

In file /var/lib/grafana/plugins/myorg-scenes-app/src/pages/HelloWorld/helloWorldScene.tsx
``` 
const queryRunner = new SceneQueryRunner({                                                                                                                                
    datasource: {                                                                                                                                                            
    type: 'yesoreyeram-infinity-datasource',                                                                                                                                 
    uid: 'yesoreyeram-infinity-datasource',                                                                                                                                  
    },                                                                                                                                                                       
    queries: [                                                                                                                                                               
      {                                                                                                                                                                      
        refId: 'C',                                                                                                                                                          
        url: '/simplescene',                                                                                                                                                 
        columns: [                                                                                                                                                           
          {                                                                                                                                                                  
           selector: "time",                                                                                                                                                 
           text: "time",                                                                                                                                                     
           type: "time"                                                                                                                                                      
         },                                                                                                                                                                  
         {                                                                                                                                                                   
           selector: "series1",                                                                                                                                              
           text: "series1",                                                                                                                                                  
           type: "number"                                                                                                                                                    
         },                                                                                                                                                                  
         {                                                                                                                                                                   
           selector: "series2",                                                                                                                                                         
           text: "series2",                                                                                                                                                             
            type: "number"                                                                                                                                                    
         },                                                                                                                                                                  
        ]                                                                                                                                                                    
      },                                                                                                                                                                     
    ],                                                                                                                                                                       
  });       
```

And here in the SceneFlexLayout:
```
        new SceneFlexItem({                                                                                                                                                  
          width: '60%',                                                                                                                                                      
          height: 400,                                                                                                                                                       
          body: PanelBuilders.timeseries()                                                                                                                                   
            .setTitle('Infinity timeseries now working 🤸')                                                                                                                     
            .setData(queryRunner2)                                                                                                                                           
            .build(),                                                                                                                                                        
        }),                     
```
This produces a timeseries graph of a dataframe like this
```
  {
    "time": 1672531200000,
    "series1": 10,
    "series2": 15
  },
  {
    "time": 1672617600000,
    "series1": 20,
    "series2": 25
  }
]
```

Here is the provisioned datasource yaml:
```
apiVersion: 1                                                                                                                                                                
                                                                                                                                                                             
datasources:                                                                                                                                                                 
- id: 3                                                                                                                                                                      
  name: "infinity"                                                                                                                                                           
  uid: "yesoreyeram-infinity-datasource"                                                                                                                                     
  type: "yesoreyeram-infinity-datasource"                                                                                                                                    
  url: "http://foobar...."                                                                                                                                      
  basicAuth: false                                                                                                                                                           
  basicAuthUser: ""                                                                                                                                                          
  isDefault: false                                                                                                                                                           
  jsonData:                                                                                                                                                                  
    global_queries: []                                                                                                                                                       
  readOnly: true                                                                                                                                                             
  apiVersion: ""                                                                                                                                                             
  overwrite: true    

```

Thank you again to the Grafana Gods, and for Scenes!
